from dorm_scheduler import *
T1, T2, T3 = 0, 1, 2

random.seed(878)

dorms = []

chw = Dorm('CHW')
dorms.append(chw)
chw.add_faculty('TSmith', 'adjunct')
chw.add_faculty('JCaditz', 'head', family = 'AFortner')
chw.add_faculty('JKellogg', 'residential')
chw.add_faculty('IBarry', 'residential', family = 'RBarry')
chw.add_faculty('PDenison', 'adjunct')
chw.assign_weekday_presets(T1, {'Wednesday':'IBarry', 'Monday':'PDenison', 'Sunday':'JCaditz'})
chw.assign_weekday_presets(T2, {'Monday':'IBarry', 'Sunday':'JCaditz'})
chw.assign_weekday_presets(T3, {'Tuesday':'IBarry', 'Sunday':'JCaditz'})
chw.add_faculty('RBarry', 'hospital', family = 'IBarry')
chw.add_faculty('AFortner', 'hospital', family = 'JCaditz')
chw.set_hospital_run_dates('1/5/2015', '2/7/2015')

twentyfive = Dorm('25')
dorms.append(twentyfive)
twentyfive.add_faculty('JKnecht', 'residential')
twentyfive.fac_instance['JKnecht'].set_unavailable_dow('Monday')
twentyfive.add_faculty('MMuller', 'residential')
twentyfive.add_faculty('GwPierce', 'adjunct')
twentyfive.add_faculty('ASalcedo', 'head')
twentyfive.add_faculty('CGarcia', 'adjunct')
twentyfive.fac_instance['CGarcia'].set_unavailable_dow('Tuesday')
twentyfive.add_faculty('JBlock', 'hospital')
twentyfive.add_faculty('KMason', 'hospital')


bothin = Dorm('BP')
dorms.append(bothin)
bothin.add_faculty('RBonning', 'adjunct')
bothin.add_faculty('RColby', 'residential')
bothin.add_faculty('Cahill', 'adjunct')
bothin.add_faculty('DSoto', 'residential')
bothin.add_faculty('AVenditta', 'head')
bothin.add_faculty('GPierce', 'hospital', family = 'SPierce')
bothin.add_faculty('SPierce', 'hospital', family = 'GPierce')

hh = Dorm('HH')
dorms.append(hh)
hh.add_faculty('NBowler', 'adjunct')
hh.add_faculty('CDonovan', 'residential')
hh.add_faculty('MPouye', 'residential')
hh.add_faculty('WRansom', 'head', family = 'JRansom')
hh.add_faculty('DWood', 'adjunct')
hh.add_faculty('CBrownlee', 'hospital')
hh.add_faculty('JRansom', 'hospital', family = 'WRansom')
hh.add_faculty('MWoehr', 'hospital')

lh = Dorm('LH')
dorms.append(lh)
lh.add_faculty('WButler', 'residential')
lh.add_faculty('AMacDonnell', 'residential')
lh.add_faculty('BSoto', 'residential')
lh.add_faculty('JDorion', 'head', 'partial', family = 'MDorion')
lh.add_faculty('MDrew', 'adjunct')
lh.add_faculty('RMack', 'hospital')
lh.add_faculty('MBradley', 'hospital')
lh.add_faculty('MDorion', 'hospital', family = 'JDorion')

sh = Dorm('SH')
dorms.append(sh)
sh.add_faculty('PCollins', 'adjunct')
sh.add_faculty('Shannon', 'head')
sh.add_faculty('FGriffin', 'adjunct', family = 'EGriffin')
sh.add_faculty('TWyatt', 'residential')
sh.add_faculty('AGolann', 'adjunct')
sh.add_faculty('MKrill', 'hospital')
sh.add_faculty('EGriffin', 'hospital', family = 'FGriffin')

for dorm in [chw]:
    dorm.make_schedule()
    dorm.get_duty_counts()
    dorm.export_duty_to_csv()
    dorm.export_hr_to_csv()